---

- name: Update Packages
  sudo: yes
  apt:
    update_cache: yes
    upgrade: dist

- name: Install Vim, Emacs, Tmux, HTop, Unzip
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ machine_standard_packages }}"

- name: Install Machine Packages
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ machine_packages }}"
