---
# tasks file for common

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define machine_standard_packages.
  set_fact:
    machine_standard_packages: "{{ __machine_standard_packages | list }}"
  when: machine_standard_packages is not defined

- name: Include OS-specific tasks.
  include: "{{ ansible_os_family }}.yml"

- name: Set Locale
  sudo: yes
  template:
    src: locale.conf.j2
    dest: /etc/locale.conf

- name: Get Localtime information
  sudo: yes
  stat: 
    path: /etc/localtime
  register: localtime

- name: Remove the localtime file
  sudo: yes
  file:
    path: /etc/localtime
    state: absent
  when: not localtime.stat.islnk

- name: Localtime Link
  sudo: yes
  file:
    src: /usr/share/zoneinfo/{{ machine_timezone }}
    dest: /etc/localtime
    state: link